<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ZrcSdkExample</AssemblyName>
    <RootNamespace>ZrcSdkExample</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Crestron.SimplSharp.SDK.Program" Version="2.21.237" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ZoomRoomSdk\ZoomRoomSdk.csproj" />
  </ItemGroup>

</Project>
